/**
 * This code has been generated by uk.ac.leeds.ccg.andyt.projects.wigb.process.WIGB_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.projects.wigb.data;
public abstract class WIGB_Wave1Or2_HHOLD_Record extends WIGB_Wave1Or2Or3Or4Or5_HHOLD_Record {
protected static Double DVBLDDEBT;

protected static Double DVBLDVAL;

protected static Double DVCACRVAL_SUM;

protected static Double DVCACTV_SUM;

protected static Double DVCAODVAL_SUM;

protected static Double DVCASVV_SUM;

protected static Double DVCAVAL_SUM;

protected static Double DVCISAV_SUM;

protected static Double DVDBRWEALTHVAL_SUM;

protected static Double DVEQHIP;

protected static Double DVEQRUPM;

protected static Double DVFBONDV_SUM;

protected static Double DVFCOLLV_SUM;

protected static Double DVFESHARES_SUM;

protected static Double DVFFASSETS_SUM;

protected static Double DVFGLTFOV_SUM;

protected static Double DVFGLTUKV_SUM;

protected static Double DVFINFLV_SUM;

protected static Double DVFINFVAL_SUM;

protected static Double DVFINFV_SUM;

protected static Double DVFINVOTV_SUM;

protected static Double DVFNSVAL_SUM;

protected static Double DVFSHOSV_SUM;

protected static Double DVFSHUKV_SUM;

protected static Double DVHRPNUM;

protected static Double DVHSEDEBT;

protected static Double DVHSEVAL;

protected static Double DVIISAV_SUM;

protected static Double DVINSV_SUM;

protected static Double DVISAVAL_SUM;

protected static Double DVKISAV_SUM;

protected static Double DVLOSDEBT;

protected static Double DVLOSVAL;

protected static Double DVLUKDEBT;

protected static Double DVLUKVAL;

protected static Double DVOPRDEBT;

protected static Double DVOPRVAL;

protected static Double DVPAVCUV_SUM;

protected static Double DVPFCURVAL_SUM;

protected static Double DVPFDDV_SUM;

protected static Double DVPINPVAL_SUM;

protected static Double DVPPVAL_SUM;

protected static Double DVSAVAL_SUM;

protected static Double DVSPEN_SUM;

protected static Double DVTOTCARVAL;

protected static Double DVTOTMOTBVAL;

protected static Double DVTOTVANVAL;

protected static Double DVVALDBT_SUM;

protected static Double DVVALDCOS_SUM;

protected static Double DVVESTV2_I;

protected static Double DVVESTV2_IFLAG;

protected static Double DVVESTV3_I;

protected static Double DVVESTV3_IFLAG;

protected static Double DVVESTV_I;

protected static Double DVVESTV_IFLAG;

protected static Double DVVOVAL_I;

protected static Double DVVOVAL_IFLAG;

protected static Double DVVPERV_I;

protected static Double DVVPERV_IFLAG;

protected static Double EINTPAY;

protected static Double EOTHIRR;

protected static Double EOTHIVA;

protected static Double EOTHIVB;

protected static Double EQFILTER;

protected static Double EQREAS1;

protected static Double EQREAS2;

protected static Double EQREAS3;

protected static Double EQREAS4;

protected static Double EQREL;

protected static Double EQREL_I;

protected static Double EQREL_IFLAG;

protected static Double EQTYPE;

protected static Double EQTYPE_I;

protected static Double EQTYPE_IFLAG;

protected static Double EQWHEN;

protected static Double EQYES_I;

protected static Double EQYES_IFLAG;

protected static Double ERECM;

protected static Double ERECMB;

protected static Double ERENTAM;

protected static Double ERENTB;

protected static Double ERVREC;

protected static Double ERVRECB;

protected static Double ERVREG;

protected static Double GCONTVLS2;

protected static Double GCPREAM;

protected static Double HFINL_SUM;

protected static Double HFINW_EXCENDW_SUM;

protected static Double HPARR_SUM;

protected static Double HRPDVAGE15;

protected static Double HRPEMPSTAT2;

protected static Double HRPIOUT1;

protected static Double HRPPART;

protected static Double HRPPARTIOUT1;

protected static Double HVALRS1;

protected static Double HVALRS2;

protected static Double HVALRS3;

protected static Double HVALRS4;

protected static Double HVALRS5;

protected static Double LNARR_SUM;

protected static Double MALL;

protected static Double MALLTY;

protected static Double MALLTY3_I;

protected static Double MALLTY3_IFLAG;

protected static Double MALLTY_I;

protected static Double MALLTY_IFLAG;

protected static Double MALL_I;

protected static Double MALL_IFLAG;

protected static Double MARRS;

protected static Double MDIFFPY;

protected static Double MENDNUM;

protected static Double MENDNUM_I;

protected static Double MENDNUM_IFLAG;

protected static Double MENDV;

protected static Double MENDVB;

protected static Double MENDVB5;

protected static Double MENDVB8;

protected static Double MENDV_I;

protected static Double MENDV_IFLAG;

protected static Double MENDW;

protected static Double MENDW3;

protected static Double MENDW_I;

protected static Double MENDW_IFLAG;

protected static Double MENDX;

protected static Double MENDY;

protected static Double MENDY5;

protected static Double MENDY8;

protected static Double MHOWPY;

protected static Double MINC12;

protected static Double MINC7;

protected static Double MINC8;

protected static Double MINC9;

protected static Double MNAME;

protected static Double MNEG;

protected static Double MNEGB;

protected static Double MNEG_I;

protected static Double MNEG_IFLAG;

protected static Double MOARR_SUM;

protected static Double MONAME;

protected static Double MPAYB;

protected static Double MPAYM;

protected static Double MPP;

protected static Double MREAS08;

protected static Double MREAS09;

protected static Double MREAS11;

protected static Double MREAS21;

protected static Double MREAS22;

protected static Double MTYPE;

protected static Double MTYPE_I;

protected static Double MTYPE_IFLAG;

protected static Double MVAL;

protected static Double MVALB;

protected static Double MVAL_I;

protected static Double MVAL_IFLAG;

protected static Double MYLFT;

protected static Double NBABY;

protected static Double NC1015;

protected static Double NC1618;

protected static Double NC5TO9;

protected static Double NCHILD;

protected static Double NCU16;

protected static Double NCUND5;

protected static Double NDEPC;

protected static Double NNDEPC;

protected static Double NUMJOB;

protected static Double NUMSSEX;

protected static Double NVESTV;

protected static Double OTHMORT;

protected static Double TOTBILLARR_SUM;

protected static Double TOTCC_SUM;

protected static Double TOTHP_SUM;

protected static Double TOTLOS_SUM;

protected static Double TOTMO_SUM;

protected static Double TOTPEN_SUM;

protected static Double TOTSC_SUM;

protected static Double T_FLNS_SUM;

protected static Double T_LNS_SUM;

protected static Double T_SLNS_SUM;

protected static Double VESTV;

protected static Double VESTV2;

protected static Double VESTV2_I;

protected static Double VESTV2_IFLAG;

protected static Double VESTV3;

protected static Double VESTV3_I;

protected static Double VESTV3_IFLAG;

protected static Double VESTV_I;

protected static Double VESTV_IFLAG;

protected static Double VESVB;

protected static Double VESVB2;

protected static Double VESVB3;

protected static Double VOTHT;

protected static Double VOTHT_I;

protected static Double VOTHT_IFLAG;

protected static Double VOTYP1_IFLAG;

protected static Double VOTYP2_IFLAG;

protected static Double VOTYP3_IFLAG;

protected static Double VOTYP4_IFLAG;

protected static Double VOTYP5;

protected static Double VOTYP5_IFLAG;

protected static Double VOVLB_I;

protected static Double VOVLB_IFLAG;

protected static Double VTYPE;

protected static Double VTYPE2_IFLAG;

protected static Double VTYPE_I;

public Double getDVBLDDEBT() {
return DVBLDDEBT;
}

public Double getDVBLDVAL() {
return DVBLDVAL;
}

public Double getDVCACRVAL_SUM() {
return DVCACRVAL_SUM;
}

public Double getDVCACTV_SUM() {
return DVCACTV_SUM;
}

public Double getDVCAODVAL_SUM() {
return DVCAODVAL_SUM;
}

public Double getDVCASVV_SUM() {
return DVCASVV_SUM;
}

public Double getDVCAVAL_SUM() {
return DVCAVAL_SUM;
}

public Double getDVCISAV_SUM() {
return DVCISAV_SUM;
}

public Double getDVDBRWEALTHVAL_SUM() {
return DVDBRWEALTHVAL_SUM;
}

public Double getDVEQHIP() {
return DVEQHIP;
}

public Double getDVEQRUPM() {
return DVEQRUPM;
}

public Double getDVFBONDV_SUM() {
return DVFBONDV_SUM;
}

public Double getDVFCOLLV_SUM() {
return DVFCOLLV_SUM;
}

public Double getDVFESHARES_SUM() {
return DVFESHARES_SUM;
}

public Double getDVFFASSETS_SUM() {
return DVFFASSETS_SUM;
}

public Double getDVFGLTFOV_SUM() {
return DVFGLTFOV_SUM;
}

public Double getDVFGLTUKV_SUM() {
return DVFGLTUKV_SUM;
}

public Double getDVFINFLV_SUM() {
return DVFINFLV_SUM;
}

public Double getDVFINFVAL_SUM() {
return DVFINFVAL_SUM;
}

public Double getDVFINFV_SUM() {
return DVFINFV_SUM;
}

public Double getDVFINVOTV_SUM() {
return DVFINVOTV_SUM;
}

public Double getDVFNSVAL_SUM() {
return DVFNSVAL_SUM;
}

public Double getDVFSHOSV_SUM() {
return DVFSHOSV_SUM;
}

public Double getDVFSHUKV_SUM() {
return DVFSHUKV_SUM;
}

public Double getDVHRPNUM() {
return DVHRPNUM;
}

public Double getDVHSEDEBT() {
return DVHSEDEBT;
}

public Double getDVHSEVAL() {
return DVHSEVAL;
}

public Double getDVIISAV_SUM() {
return DVIISAV_SUM;
}

public Double getDVINSV_SUM() {
return DVINSV_SUM;
}

public Double getDVISAVAL_SUM() {
return DVISAVAL_SUM;
}

public Double getDVKISAV_SUM() {
return DVKISAV_SUM;
}

public Double getDVLOSDEBT() {
return DVLOSDEBT;
}

public Double getDVLOSVAL() {
return DVLOSVAL;
}

public Double getDVLUKDEBT() {
return DVLUKDEBT;
}

public Double getDVLUKVAL() {
return DVLUKVAL;
}

public Double getDVOPRDEBT() {
return DVOPRDEBT;
}

public Double getDVOPRVAL() {
return DVOPRVAL;
}

public Double getDVPAVCUV_SUM() {
return DVPAVCUV_SUM;
}

public Double getDVPFCURVAL_SUM() {
return DVPFCURVAL_SUM;
}

public Double getDVPFDDV_SUM() {
return DVPFDDV_SUM;
}

public Double getDVPINPVAL_SUM() {
return DVPINPVAL_SUM;
}

public Double getDVPPVAL_SUM() {
return DVPPVAL_SUM;
}

public Double getDVSAVAL_SUM() {
return DVSAVAL_SUM;
}

public Double getDVSPEN_SUM() {
return DVSPEN_SUM;
}

public Double getDVTOTCARVAL() {
return DVTOTCARVAL;
}

public Double getDVTOTMOTBVAL() {
return DVTOTMOTBVAL;
}

public Double getDVTOTVANVAL() {
return DVTOTVANVAL;
}

public Double getDVVALDBT_SUM() {
return DVVALDBT_SUM;
}

public Double getDVVALDCOS_SUM() {
return DVVALDCOS_SUM;
}

public Double getDVVESTV2_I() {
return DVVESTV2_I;
}

public Double getDVVESTV2_IFLAG() {
return DVVESTV2_IFLAG;
}

public Double getDVVESTV3_I() {
return DVVESTV3_I;
}

public Double getDVVESTV3_IFLAG() {
return DVVESTV3_IFLAG;
}

public Double getDVVESTV_I() {
return DVVESTV_I;
}

public Double getDVVESTV_IFLAG() {
return DVVESTV_IFLAG;
}

public Double getDVVOVAL_I() {
return DVVOVAL_I;
}

public Double getDVVOVAL_IFLAG() {
return DVVOVAL_IFLAG;
}

public Double getDVVPERV_I() {
return DVVPERV_I;
}

public Double getDVVPERV_IFLAG() {
return DVVPERV_IFLAG;
}

public Double getEINTPAY() {
return EINTPAY;
}

public Double getEOTHIRR() {
return EOTHIRR;
}

public Double getEOTHIVA() {
return EOTHIVA;
}

public Double getEOTHIVB() {
return EOTHIVB;
}

public Double getEQFILTER() {
return EQFILTER;
}

public Double getEQREAS1() {
return EQREAS1;
}

public Double getEQREAS2() {
return EQREAS2;
}

public Double getEQREAS3() {
return EQREAS3;
}

public Double getEQREAS4() {
return EQREAS4;
}

public Double getEQREL() {
return EQREL;
}

public Double getEQREL_I() {
return EQREL_I;
}

public Double getEQREL_IFLAG() {
return EQREL_IFLAG;
}

public Double getEQTYPE() {
return EQTYPE;
}

public Double getEQTYPE_I() {
return EQTYPE_I;
}

public Double getEQTYPE_IFLAG() {
return EQTYPE_IFLAG;
}

public Double getEQWHEN() {
return EQWHEN;
}

public Double getEQYES_I() {
return EQYES_I;
}

public Double getEQYES_IFLAG() {
return EQYES_IFLAG;
}

public Double getERECM() {
return ERECM;
}

public Double getERECMB() {
return ERECMB;
}

public Double getERENTAM() {
return ERENTAM;
}

public Double getERENTB() {
return ERENTB;
}

public Double getERVREC() {
return ERVREC;
}

public Double getERVRECB() {
return ERVRECB;
}

public Double getERVREG() {
return ERVREG;
}

public Double getGCONTVLS2() {
return GCONTVLS2;
}

public Double getGCPREAM() {
return GCPREAM;
}

public Double getHFINL_SUM() {
return HFINL_SUM;
}

public Double getHFINW_EXCENDW_SUM() {
return HFINW_EXCENDW_SUM;
}

public Double getHPARR_SUM() {
return HPARR_SUM;
}

public Double getHRPDVAGE15() {
return HRPDVAGE15;
}

public Double getHRPEMPSTAT2() {
return HRPEMPSTAT2;
}

public Double getHRPIOUT1() {
return HRPIOUT1;
}

public Double getHRPPART() {
return HRPPART;
}

public Double getHRPPARTIOUT1() {
return HRPPARTIOUT1;
}

public Double getHVALRS1() {
return HVALRS1;
}

public Double getHVALRS2() {
return HVALRS2;
}

public Double getHVALRS3() {
return HVALRS3;
}

public Double getHVALRS4() {
return HVALRS4;
}

public Double getHVALRS5() {
return HVALRS5;
}

public Double getLNARR_SUM() {
return LNARR_SUM;
}

public Double getMALL() {
return MALL;
}

public Double getMALLTY() {
return MALLTY;
}

public Double getMALLTY3_I() {
return MALLTY3_I;
}

public Double getMALLTY3_IFLAG() {
return MALLTY3_IFLAG;
}

public Double getMALLTY_I() {
return MALLTY_I;
}

public Double getMALLTY_IFLAG() {
return MALLTY_IFLAG;
}

public Double getMALL_I() {
return MALL_I;
}

public Double getMALL_IFLAG() {
return MALL_IFLAG;
}

public Double getMARRS() {
return MARRS;
}

public Double getMDIFFPY() {
return MDIFFPY;
}

public Double getMENDNUM() {
return MENDNUM;
}

public Double getMENDNUM_I() {
return MENDNUM_I;
}

public Double getMENDNUM_IFLAG() {
return MENDNUM_IFLAG;
}

public Double getMENDV() {
return MENDV;
}

public Double getMENDVB() {
return MENDVB;
}

public Double getMENDVB5() {
return MENDVB5;
}

public Double getMENDVB8() {
return MENDVB8;
}

public Double getMENDV_I() {
return MENDV_I;
}

public Double getMENDV_IFLAG() {
return MENDV_IFLAG;
}

public Double getMENDW() {
return MENDW;
}

public Double getMENDW3() {
return MENDW3;
}

public Double getMENDW_I() {
return MENDW_I;
}

public Double getMENDW_IFLAG() {
return MENDW_IFLAG;
}

public Double getMENDX() {
return MENDX;
}

public Double getMENDY() {
return MENDY;
}

public Double getMENDY5() {
return MENDY5;
}

public Double getMENDY8() {
return MENDY8;
}

public Double getMHOWPY() {
return MHOWPY;
}

public Double getMINC12() {
return MINC12;
}

public Double getMINC7() {
return MINC7;
}

public Double getMINC8() {
return MINC8;
}

public Double getMINC9() {
return MINC9;
}

public Double getMNAME() {
return MNAME;
}

public Double getMNEG() {
return MNEG;
}

public Double getMNEGB() {
return MNEGB;
}

public Double getMNEG_I() {
return MNEG_I;
}

public Double getMNEG_IFLAG() {
return MNEG_IFLAG;
}

public Double getMOARR_SUM() {
return MOARR_SUM;
}

public Double getMONAME() {
return MONAME;
}

public Double getMPAYB() {
return MPAYB;
}

public Double getMPAYM() {
return MPAYM;
}

public Double getMPP() {
return MPP;
}

public Double getMREAS08() {
return MREAS08;
}

public Double getMREAS09() {
return MREAS09;
}

public Double getMREAS11() {
return MREAS11;
}

public Double getMREAS21() {
return MREAS21;
}

public Double getMREAS22() {
return MREAS22;
}

public Double getMTYPE() {
return MTYPE;
}

public Double getMTYPE_I() {
return MTYPE_I;
}

public Double getMTYPE_IFLAG() {
return MTYPE_IFLAG;
}

public Double getMVAL() {
return MVAL;
}

public Double getMVALB() {
return MVALB;
}

public Double getMVAL_I() {
return MVAL_I;
}

public Double getMVAL_IFLAG() {
return MVAL_IFLAG;
}

public Double getMYLFT() {
return MYLFT;
}

public Double getNBABY() {
return NBABY;
}

public Double getNC1015() {
return NC1015;
}

public Double getNC1618() {
return NC1618;
}

public Double getNC5TO9() {
return NC5TO9;
}

public Double getNCHILD() {
return NCHILD;
}

public Double getNCU16() {
return NCU16;
}

public Double getNCUND5() {
return NCUND5;
}

public Double getNDEPC() {
return NDEPC;
}

public Double getNNDEPC() {
return NNDEPC;
}

public Double getNUMJOB() {
return NUMJOB;
}

public Double getNUMSSEX() {
return NUMSSEX;
}

public Double getNVESTV() {
return NVESTV;
}

public Double getOTHMORT() {
return OTHMORT;
}

public Double getTOTBILLARR_SUM() {
return TOTBILLARR_SUM;
}

public Double getTOTCC_SUM() {
return TOTCC_SUM;
}

public Double getTOTHP_SUM() {
return TOTHP_SUM;
}

public Double getTOTLOS_SUM() {
return TOTLOS_SUM;
}

public Double getTOTMO_SUM() {
return TOTMO_SUM;
}

public Double getTOTPEN_SUM() {
return TOTPEN_SUM;
}

public Double getTOTSC_SUM() {
return TOTSC_SUM;
}

public Double getT_FLNS_SUM() {
return T_FLNS_SUM;
}

public Double getT_LNS_SUM() {
return T_LNS_SUM;
}

public Double getT_SLNS_SUM() {
return T_SLNS_SUM;
}

public Double getVESTV() {
return VESTV;
}

public Double getVESTV2() {
return VESTV2;
}

public Double getVESTV2_I() {
return VESTV2_I;
}

public Double getVESTV2_IFLAG() {
return VESTV2_IFLAG;
}

public Double getVESTV3() {
return VESTV3;
}

public Double getVESTV3_I() {
return VESTV3_I;
}

public Double getVESTV3_IFLAG() {
return VESTV3_IFLAG;
}

public Double getVESTV_I() {
return VESTV_I;
}

public Double getVESTV_IFLAG() {
return VESTV_IFLAG;
}

public Double getVESVB() {
return VESVB;
}

public Double getVESVB2() {
return VESVB2;
}

public Double getVESVB3() {
return VESVB3;
}

public Double getVOTHT() {
return VOTHT;
}

public Double getVOTHT_I() {
return VOTHT_I;
}

public Double getVOTHT_IFLAG() {
return VOTHT_IFLAG;
}

public Double getVOTYP1_IFLAG() {
return VOTYP1_IFLAG;
}

public Double getVOTYP2_IFLAG() {
return VOTYP2_IFLAG;
}

public Double getVOTYP3_IFLAG() {
return VOTYP3_IFLAG;
}

public Double getVOTYP4_IFLAG() {
return VOTYP4_IFLAG;
}

public Double getVOTYP5() {
return VOTYP5;
}

public Double getVOTYP5_IFLAG() {
return VOTYP5_IFLAG;
}

public Double getVOVLB_I() {
return VOVLB_I;
}

public Double getVOVLB_IFLAG() {
return VOVLB_IFLAG;
}

public Double getVTYPE() {
return VTYPE;
}

public Double getVTYPE2_IFLAG() {
return VTYPE2_IFLAG;
}

public Double getVTYPE_I() {
return VTYPE_I;
}

}
