/**
 * This code has been generated by uk.ac.leeds.ccg.andyt.projects.wigb.process.WIGB_JavaCodeGenerator
 */
package uk.ac.leeds.ccg.andyt.projects.wigb.data.waas;
public abstract class WIGB_Wave4Or5_HHOLD_Record extends WIGB_Wave3Or4Or5_HHOLD_Record {
protected static Double BRIDLN1;

protected static Double BRIDLN2;

protected static Double BRIDLN3;

protected static Double CASEW4;

protected static Double DVBENEFITANNUAL_AGGR;

protected static Double EQVALB_I;

protected static Double EQVALB_IFLAG;

protected static Double HRPDVAGE;

protected static Double HRPDVECACT;

protected static Double HRPIOUT1;

protected static Double HRPPARTIOUT1;

protected static Double MALL1;

protected static Double MALL1_I;

protected static Double MALL1_IFLAG;

protected static Double MALLTY1;

protected static Double MALLTY1_I;

protected static Double MALLTY1_IFLAG;

protected static Double MARR2YR1;

protected static Double MARR2YR2;

protected static Double MARR2YR3;

protected static Double MARRCL01;

protected static Double MARRCL02;

protected static Double MARRCL12;

protected static Double MARRS1;

protected static Double MARRSV1;

protected static Double MENDNUM1;

protected static Double MENDNUM1_I;

protected static Double MENDNUM1_IFLAG;

protected static Double MENDV1;

protected static Double MENDV1_I;

protected static Double MENDV1_IFLAG;

protected static Double MENDVB1;

protected static Double MENDVB11_I;

protected static Double MENDVB11_IFLAG;

protected static Double MENDVB1_I;

protected static Double MENDVB1_IFLAG;

protected static Double MENDVB2_I;

protected static Double MENDVB2_IFLAG;

protected static Double MENDVB3_I;

protected static Double MENDVB3_IFLAG;

protected static Double MENDVB4_I;

protected static Double MENDVB4_IFLAG;

protected static Double MENDVB5_I;

protected static Double MENDVB5_IFLAG;

protected static Double MENDVB6_I;

protected static Double MENDVB6_IFLAG;

protected static Double MENDVB7_I;

protected static Double MENDVB7_IFLAG;

protected static Double MENDVB8_I;

protected static Double MENDVB8_IFLAG;

protected static Double MENDVB9_I;

protected static Double MENDVB9_IFLAG;

protected static Double MENDW1;

protected static Double MENDW1_I;

protected static Double MENDW1_IFLAG;

protected static Double MENDW3;

protected static Double MENDX1;

protected static Double MENDY1;

protected static Double MHOWPY1;

protected static Double MINVW1;

protected static Double MINVW2;

protected static Double MINVW3;

protected static Double MNAME1;

protected static Double MNEG1;

protected static Double MNEG1_I;

protected static Double MNEG1_IFLAG;

protected static Double MNEGB1;

protected static Double MONAME1;

protected static Double MONTHW1;

protected static Double MONTHW2;

protected static Double MONTHW3;

protected static Double MPAYB1;

protected static Double MPAYM1;

protected static Double MPOLICY1;

protected static Double MPOLICY2;

protected static Double MPP1;

protected static Double MTYPE1;

protected static Double MTYPE1_I;

protected static Double MTYPE1_IFLAG;

protected static Double MVAL1;

protected static Double MVAL1_I;

protected static Double MVAL1_IFLAG;

protected static Double MVALB1;

protected static Double MYIFCH1;

protected static Double MYLFT1;

protected static Double VTYPE1;

protected static Double YEARW1;

protected static Double YEARW2;

protected static Double YEARW3;

protected final void initBRIDLN1(String s) {
if (!s.trim().isEmpty()) {
BRIDLN1 = new Double(s);
}
}

protected final void initBRIDLN2(String s) {
if (!s.trim().isEmpty()) {
BRIDLN2 = new Double(s);
}
}

protected final void initBRIDLN3(String s) {
if (!s.trim().isEmpty()) {
BRIDLN3 = new Double(s);
}
}

protected final void initCASEW4(String s) {
if (!s.trim().isEmpty()) {
CASEW4 = new Double(s);
}
}

protected final void initDVBENEFITANNUAL_AGGR(String s) {
if (!s.trim().isEmpty()) {
DVBENEFITANNUAL_AGGR = new Double(s);
}
}

protected final void initEQVALB_I(String s) {
if (!s.trim().isEmpty()) {
EQVALB_I = new Double(s);
}
}

protected final void initEQVALB_IFLAG(String s) {
if (!s.trim().isEmpty()) {
EQVALB_IFLAG = new Double(s);
}
}

protected final void initHRPDVAGE(String s) {
if (!s.trim().isEmpty()) {
HRPDVAGE = new Double(s);
}
}

protected final void initHRPDVECACT(String s) {
if (!s.trim().isEmpty()) {
HRPDVECACT = new Double(s);
}
}

protected final void initHRPIOUT1(String s) {
if (!s.trim().isEmpty()) {
HRPIOUT1 = new Double(s);
}
}

protected final void initHRPPARTIOUT1(String s) {
if (!s.trim().isEmpty()) {
HRPPARTIOUT1 = new Double(s);
}
}

protected final void initMALL1(String s) {
if (!s.trim().isEmpty()) {
MALL1 = new Double(s);
}
}

protected final void initMALL1_I(String s) {
if (!s.trim().isEmpty()) {
MALL1_I = new Double(s);
}
}

protected final void initMALL1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MALL1_IFLAG = new Double(s);
}
}

protected final void initMALLTY1(String s) {
if (!s.trim().isEmpty()) {
MALLTY1 = new Double(s);
}
}

protected final void initMALLTY1_I(String s) {
if (!s.trim().isEmpty()) {
MALLTY1_I = new Double(s);
}
}

protected final void initMALLTY1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MALLTY1_IFLAG = new Double(s);
}
}

protected final void initMARR2YR1(String s) {
if (!s.trim().isEmpty()) {
MARR2YR1 = new Double(s);
}
}

protected final void initMARR2YR2(String s) {
if (!s.trim().isEmpty()) {
MARR2YR2 = new Double(s);
}
}

protected final void initMARR2YR3(String s) {
if (!s.trim().isEmpty()) {
MARR2YR3 = new Double(s);
}
}

protected final void initMARRCL01(String s) {
if (!s.trim().isEmpty()) {
MARRCL01 = new Double(s);
}
}

protected final void initMARRCL02(String s) {
if (!s.trim().isEmpty()) {
MARRCL02 = new Double(s);
}
}

protected final void initMARRCL12(String s) {
if (!s.trim().isEmpty()) {
MARRCL12 = new Double(s);
}
}

protected final void initMARRS1(String s) {
if (!s.trim().isEmpty()) {
MARRS1 = new Double(s);
}
}

protected final void initMARRSV1(String s) {
if (!s.trim().isEmpty()) {
MARRSV1 = new Double(s);
}
}

protected final void initMENDNUM1(String s) {
if (!s.trim().isEmpty()) {
MENDNUM1 = new Double(s);
}
}

protected final void initMENDNUM1_I(String s) {
if (!s.trim().isEmpty()) {
MENDNUM1_I = new Double(s);
}
}

protected final void initMENDNUM1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDNUM1_IFLAG = new Double(s);
}
}

protected final void initMENDV1(String s) {
if (!s.trim().isEmpty()) {
MENDV1 = new Double(s);
}
}

protected final void initMENDV1_I(String s) {
if (!s.trim().isEmpty()) {
MENDV1_I = new Double(s);
}
}

protected final void initMENDV1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDV1_IFLAG = new Double(s);
}
}

protected final void initMENDVB1(String s) {
if (!s.trim().isEmpty()) {
MENDVB1 = new Double(s);
}
}

protected final void initMENDVB11_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB11_I = new Double(s);
}
}

protected final void initMENDVB11_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB11_IFLAG = new Double(s);
}
}

protected final void initMENDVB1_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB1_I = new Double(s);
}
}

protected final void initMENDVB1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB1_IFLAG = new Double(s);
}
}

protected final void initMENDVB2_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB2_I = new Double(s);
}
}

protected final void initMENDVB2_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB2_IFLAG = new Double(s);
}
}

protected final void initMENDVB3_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB3_I = new Double(s);
}
}

protected final void initMENDVB3_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB3_IFLAG = new Double(s);
}
}

protected final void initMENDVB4_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB4_I = new Double(s);
}
}

protected final void initMENDVB4_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB4_IFLAG = new Double(s);
}
}

protected final void initMENDVB5_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB5_I = new Double(s);
}
}

protected final void initMENDVB5_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB5_IFLAG = new Double(s);
}
}

protected final void initMENDVB6_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB6_I = new Double(s);
}
}

protected final void initMENDVB6_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB6_IFLAG = new Double(s);
}
}

protected final void initMENDVB7_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB7_I = new Double(s);
}
}

protected final void initMENDVB7_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB7_IFLAG = new Double(s);
}
}

protected final void initMENDVB8_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB8_I = new Double(s);
}
}

protected final void initMENDVB8_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB8_IFLAG = new Double(s);
}
}

protected final void initMENDVB9_I(String s) {
if (!s.trim().isEmpty()) {
MENDVB9_I = new Double(s);
}
}

protected final void initMENDVB9_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDVB9_IFLAG = new Double(s);
}
}

protected final void initMENDW1(String s) {
if (!s.trim().isEmpty()) {
MENDW1 = new Double(s);
}
}

protected final void initMENDW1_I(String s) {
if (!s.trim().isEmpty()) {
MENDW1_I = new Double(s);
}
}

protected final void initMENDW1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MENDW1_IFLAG = new Double(s);
}
}

protected final void initMENDW3(String s) {
if (!s.trim().isEmpty()) {
MENDW3 = new Double(s);
}
}

protected final void initMENDX1(String s) {
if (!s.trim().isEmpty()) {
MENDX1 = new Double(s);
}
}

protected final void initMENDY1(String s) {
if (!s.trim().isEmpty()) {
MENDY1 = new Double(s);
}
}

protected final void initMHOWPY1(String s) {
if (!s.trim().isEmpty()) {
MHOWPY1 = new Double(s);
}
}

protected final void initMINVW1(String s) {
if (!s.trim().isEmpty()) {
MINVW1 = new Double(s);
}
}

protected final void initMINVW2(String s) {
if (!s.trim().isEmpty()) {
MINVW2 = new Double(s);
}
}

protected final void initMINVW3(String s) {
if (!s.trim().isEmpty()) {
MINVW3 = new Double(s);
}
}

protected final void initMNAME1(String s) {
if (!s.trim().isEmpty()) {
MNAME1 = new Double(s);
}
}

protected final void initMNEG1(String s) {
if (!s.trim().isEmpty()) {
MNEG1 = new Double(s);
}
}

protected final void initMNEG1_I(String s) {
if (!s.trim().isEmpty()) {
MNEG1_I = new Double(s);
}
}

protected final void initMNEG1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MNEG1_IFLAG = new Double(s);
}
}

protected final void initMNEGB1(String s) {
if (!s.trim().isEmpty()) {
MNEGB1 = new Double(s);
}
}

protected final void initMONAME1(String s) {
if (!s.trim().isEmpty()) {
MONAME1 = new Double(s);
}
}

protected final void initMONTHW1(String s) {
if (!s.trim().isEmpty()) {
MONTHW1 = new Double(s);
}
}

protected final void initMONTHW2(String s) {
if (!s.trim().isEmpty()) {
MONTHW2 = new Double(s);
}
}

protected final void initMONTHW3(String s) {
if (!s.trim().isEmpty()) {
MONTHW3 = new Double(s);
}
}

protected final void initMPAYB1(String s) {
if (!s.trim().isEmpty()) {
MPAYB1 = new Double(s);
}
}

protected final void initMPAYM1(String s) {
if (!s.trim().isEmpty()) {
MPAYM1 = new Double(s);
}
}

protected final void initMPOLICY1(String s) {
if (!s.trim().isEmpty()) {
MPOLICY1 = new Double(s);
}
}

protected final void initMPOLICY2(String s) {
if (!s.trim().isEmpty()) {
MPOLICY2 = new Double(s);
}
}

protected final void initMPP1(String s) {
if (!s.trim().isEmpty()) {
MPP1 = new Double(s);
}
}

protected final void initMTYPE1(String s) {
if (!s.trim().isEmpty()) {
MTYPE1 = new Double(s);
}
}

protected final void initMTYPE1_I(String s) {
if (!s.trim().isEmpty()) {
MTYPE1_I = new Double(s);
}
}

protected final void initMTYPE1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MTYPE1_IFLAG = new Double(s);
}
}

protected final void initMVAL1(String s) {
if (!s.trim().isEmpty()) {
MVAL1 = new Double(s);
}
}

protected final void initMVAL1_I(String s) {
if (!s.trim().isEmpty()) {
MVAL1_I = new Double(s);
}
}

protected final void initMVAL1_IFLAG(String s) {
if (!s.trim().isEmpty()) {
MVAL1_IFLAG = new Double(s);
}
}

protected final void initMVALB1(String s) {
if (!s.trim().isEmpty()) {
MVALB1 = new Double(s);
}
}

protected final void initMYIFCH1(String s) {
if (!s.trim().isEmpty()) {
MYIFCH1 = new Double(s);
}
}

protected final void initMYLFT1(String s) {
if (!s.trim().isEmpty()) {
MYLFT1 = new Double(s);
}
}

protected final void initVTYPE1(String s) {
if (!s.trim().isEmpty()) {
VTYPE1 = new Double(s);
}
}

protected final void initYEARW1(String s) {
if (!s.trim().isEmpty()) {
YEARW1 = new Double(s);
}
}

protected final void initYEARW2(String s) {
if (!s.trim().isEmpty()) {
YEARW2 = new Double(s);
}
}

protected final void initYEARW3(String s) {
if (!s.trim().isEmpty()) {
YEARW3 = new Double(s);
}
}

public Double getBRIDLN1() {
return BRIDLN1;
}

public Double getBRIDLN2() {
return BRIDLN2;
}

public Double getBRIDLN3() {
return BRIDLN3;
}

public Double getCASEW4() {
return CASEW4;
}

public Double getDVBENEFITANNUAL_AGGR() {
return DVBENEFITANNUAL_AGGR;
}

public Double getEQVALB_I() {
return EQVALB_I;
}

public Double getEQVALB_IFLAG() {
return EQVALB_IFLAG;
}

public Double getHRPDVAGE() {
return HRPDVAGE;
}

public Double getHRPDVECACT() {
return HRPDVECACT;
}

public Double getHRPIOUT1() {
return HRPIOUT1;
}

public Double getHRPPARTIOUT1() {
return HRPPARTIOUT1;
}

public Double getMALL1() {
return MALL1;
}

public Double getMALL1_I() {
return MALL1_I;
}

public Double getMALL1_IFLAG() {
return MALL1_IFLAG;
}

public Double getMALLTY1() {
return MALLTY1;
}

public Double getMALLTY1_I() {
return MALLTY1_I;
}

public Double getMALLTY1_IFLAG() {
return MALLTY1_IFLAG;
}

public Double getMARR2YR1() {
return MARR2YR1;
}

public Double getMARR2YR2() {
return MARR2YR2;
}

public Double getMARR2YR3() {
return MARR2YR3;
}

public Double getMARRCL01() {
return MARRCL01;
}

public Double getMARRCL02() {
return MARRCL02;
}

public Double getMARRCL12() {
return MARRCL12;
}

public Double getMARRS1() {
return MARRS1;
}

public Double getMARRSV1() {
return MARRSV1;
}

public Double getMENDNUM1() {
return MENDNUM1;
}

public Double getMENDNUM1_I() {
return MENDNUM1_I;
}

public Double getMENDNUM1_IFLAG() {
return MENDNUM1_IFLAG;
}

public Double getMENDV1() {
return MENDV1;
}

public Double getMENDV1_I() {
return MENDV1_I;
}

public Double getMENDV1_IFLAG() {
return MENDV1_IFLAG;
}

public Double getMENDVB1() {
return MENDVB1;
}

public Double getMENDVB11_I() {
return MENDVB11_I;
}

public Double getMENDVB11_IFLAG() {
return MENDVB11_IFLAG;
}

public Double getMENDVB1_I() {
return MENDVB1_I;
}

public Double getMENDVB1_IFLAG() {
return MENDVB1_IFLAG;
}

public Double getMENDVB2_I() {
return MENDVB2_I;
}

public Double getMENDVB2_IFLAG() {
return MENDVB2_IFLAG;
}

public Double getMENDVB3_I() {
return MENDVB3_I;
}

public Double getMENDVB3_IFLAG() {
return MENDVB3_IFLAG;
}

public Double getMENDVB4_I() {
return MENDVB4_I;
}

public Double getMENDVB4_IFLAG() {
return MENDVB4_IFLAG;
}

public Double getMENDVB5_I() {
return MENDVB5_I;
}

public Double getMENDVB5_IFLAG() {
return MENDVB5_IFLAG;
}

public Double getMENDVB6_I() {
return MENDVB6_I;
}

public Double getMENDVB6_IFLAG() {
return MENDVB6_IFLAG;
}

public Double getMENDVB7_I() {
return MENDVB7_I;
}

public Double getMENDVB7_IFLAG() {
return MENDVB7_IFLAG;
}

public Double getMENDVB8_I() {
return MENDVB8_I;
}

public Double getMENDVB8_IFLAG() {
return MENDVB8_IFLAG;
}

public Double getMENDVB9_I() {
return MENDVB9_I;
}

public Double getMENDVB9_IFLAG() {
return MENDVB9_IFLAG;
}

public Double getMENDW1() {
return MENDW1;
}

public Double getMENDW1_I() {
return MENDW1_I;
}

public Double getMENDW1_IFLAG() {
return MENDW1_IFLAG;
}

public Double getMENDW3() {
return MENDW3;
}

public Double getMENDX1() {
return MENDX1;
}

public Double getMENDY1() {
return MENDY1;
}

public Double getMHOWPY1() {
return MHOWPY1;
}

public Double getMINVW1() {
return MINVW1;
}

public Double getMINVW2() {
return MINVW2;
}

public Double getMINVW3() {
return MINVW3;
}

public Double getMNAME1() {
return MNAME1;
}

public Double getMNEG1() {
return MNEG1;
}

public Double getMNEG1_I() {
return MNEG1_I;
}

public Double getMNEG1_IFLAG() {
return MNEG1_IFLAG;
}

public Double getMNEGB1() {
return MNEGB1;
}

public Double getMONAME1() {
return MONAME1;
}

public Double getMONTHW1() {
return MONTHW1;
}

public Double getMONTHW2() {
return MONTHW2;
}

public Double getMONTHW3() {
return MONTHW3;
}

public Double getMPAYB1() {
return MPAYB1;
}

public Double getMPAYM1() {
return MPAYM1;
}

public Double getMPOLICY1() {
return MPOLICY1;
}

public Double getMPOLICY2() {
return MPOLICY2;
}

public Double getMPP1() {
return MPP1;
}

public Double getMTYPE1() {
return MTYPE1;
}

public Double getMTYPE1_I() {
return MTYPE1_I;
}

public Double getMTYPE1_IFLAG() {
return MTYPE1_IFLAG;
}

public Double getMVAL1() {
return MVAL1;
}

public Double getMVAL1_I() {
return MVAL1_I;
}

public Double getMVAL1_IFLAG() {
return MVAL1_IFLAG;
}

public Double getMVALB1() {
return MVALB1;
}

public Double getMYIFCH1() {
return MYIFCH1;
}

public Double getMYLFT1() {
return MYLFT1;
}

public Double getVTYPE1() {
return VTYPE1;
}

public Double getYEARW1() {
return YEARW1;
}

public Double getYEARW2() {
return YEARW2;
}

public Double getYEARW3() {
return YEARW3;
}

}
